# name: Daily Task Sync

# on:
#   schedule:
#     - cron: '2 0 * * *'  # Runs at 00:02 AM UTC daily
#   workflow_dispatch:

# jobs:
#   run-task-sync:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Set up Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: '3.10'

#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt

#     - name: Run sync_tasks.py
#       env:
#         MONGO_URI: ${{ secrets.MONGO_URI }}
#       run: |
#         python sync_tasks.py
